Added support for arm64
I had to add -Wno-error=implicit-function-declaration because on only arm64 the implicit
function declaration of locale_charset in gg_utf8.c became an error.
armv7:
gg_utf8.c:92:12: warning: implicit declaration of function 'locale_charset' is invalid in C99 [-Wimplicit-function-declaration]
arm64:
gg_utf8.c:92:12: warning: implicit declaration of function 'locale_charset' is invalid in C99 [-Werror, -Wimplicit-function-declaration]